apiVersion: v1
kind: ConfigMap
metadata:
  name: logger-config
data:
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "admin"
  POSTGRES_DB: "db"
  PORT: "5432"
  PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
  PGADMIN_DEFAULT_PASSWORD: "admin"
  HOST: "db-service"
