services:
  database:
    image: postgres:14-alpine
    container_name: logger-postgres
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    volumes:
      - pgadmin-data-pings:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8888:80"
  logger-service:
    image: robert076/logger:despicable-me-2
    container_name: logger-service
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - HOST=database                           # bridge network so they see eachother by service name
      - PORT=${PORT}
    ports:
      - "1234:1234"

volumes:
  db_data:
  pgadmin-data-pings: